export const LOAD_LIST_PRODUCTS = 'LOAD_LIST_PRODUCTS';
export const EDIT_DATA_PRODUCT = 'EDIT_DATA_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';